const msp = [
    {
        "commodity":"jowar",
        "yearone":1815,
        "yeartwo":1868,
    },
    {
        "commodity":"bajra",
        "yearone":2000,
        "yeartwo":2150,
    },
    {
        "commodity":"maize",
        "yearone":1760,
        "yeartwo":1850,
    },
    {
        "commodity":"ragi",
        "yearone":3150,
        "yeartwo":3295,
    },
    {
        "commodity":"toor",
        "yearone":5800,
        "yeartwo":6000,
    },
    {
        "commodity":"moong",
        "yearone":7050,
        "yeartwo":7196,
    },
    {
        "commodity":"urad",
        "yearone":5700,
        "yeartwo":6000,
    },
    {
        "commodity":"cotton",
        "yearone":5255,
        "yeartwo":5515,
    },
    {
        "commodity":"groundnut",
        "yearone":5090,
        "yeartwo":5275,
    },
    {
        "commodity":"sunflower-seed",
        "yearone":5650,
        "yeartwo":5885,
    },
    {
        "commodity":"wheat",
        "yearone":1925,
        "yeartwo":1975,
    },
]

export default msp